### ISSUE TITLE
Removing init.groovy.d/ files doesn't remove them from persisted master storage

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#21]
Related to this issue in Sentry: https://sentry.io/codevalet/codevalet/issues/334308607/

```
ConcurrentModificationException: None
    at java.util.Hashtable$Enumerator.next(Hashtable.java:1378)
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.toList(DefaultGroovyMethods.java:2945)
    at org.codehaus.groovy.runtime.dgm$661.invoke
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
...
(29 additional frame(s) were not displayed)
```

This appears to be an old version of `configure-sentry.groovy`, which shouldn't exist anymore. The `jenkins/jenkins;lts-alpine` hackery with `.override` files is helpful for updating existing files, but nothing *removes* old files which have been removed from the container.

**Comment by rtyler** [comment]
One solution to this which might be easiest in the short-term is to create an empty file instead of removing the previous file :frowning:
