### ISSUE TITLE
Default Git implementation should be JGit "GitException: Error launching git whatchanged"

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#25]
https://sentry.io/codevalet/codevalet/issues/334473308/

Some errors with auto-favoriting because the instance doesn't have `git` installed properly, as far as I can tell.

```
GitException: Error launching git whatchanged
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$6.execute(CliGitAPIImpl.java:907)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
    at hudson.remoting.UserRequest.perform(UserRequest.java:181)
    at hudson.remoting.UserRequest.perform(UserRequest.java:52)
...
(29 additional frame(s) were not displayed)

Unexpected error when retrieving changeset
```

**Comment by rtyler** [comment]
![default-git](https://user-images.githubusercontent.com/26594/29643954-58e110fe-8827-11e7-9468-9f048af5077e.png)

The above is from the admin area on an instance.
