### ISSUE TITLE
NullPointerException: Cannot invoke method addHandler() on null object

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#29]
https://sentry.io/codevalet/codevalet/issues/334620935/

```
NullPointerException: Cannot invoke method addHandler() on null object
    at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
...
(44 additional frame(s) were not displayed)

A thread (Thread-4/24) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
```

**Comment by rtyler** [comment]
This was fixed in the `sentry-plugin` repo
