### ISSUE TITLE
Azure VM Agents appears to have changed: GroovyRuntimeException: Could not find matching constructor for: com.microsoft.azure.vmagent.AzureVMAgentTemplate(java.la...

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#59]
https://sentry.io/codevalet/codevalet/issues/336412430/

```
GroovyRuntimeException: Could not find matching constructor for: com.microsoft.azure.vmagent.AzureVMAgentTemplate(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.Boolean, com.microsoft.azure.vmagent.AzureVMAgentTemplate$ImageReferenceTypeClass, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.String, java.lang.Boolean, java.lang.Boolean)
    at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1732)
    at groovy.lang.MetaClassImpl.invokeConstructor(MetaClassImpl.java:1532)
    at org.codehaus.groovy.runtime.callsite.MetaClassConstructorSite.callConstructor(MetaClassConstructorSite.java:49)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
...
(19 additional frame(s) were not displayed)

Failed to run script file:/usr/share/jenkins/ref/init.groovy.d/setup-azure-cloud.groovy
```

**Comment by rtyler** [comment]
e7d6ce09da60ae21462aff0f9b758d33f0a435fd
