### ISSUE TITLE
MissingPropertyException: No such property: DEFAULT_MANAGEMENT_URL for class: com.microsoft.azure.util.AzureCredentials$Con...

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#61]
https://sentry.io/codevalet/codevalet/issues/411543219/

```
MissingPropertyException: No such property: DEFAULT_MANAGEMENT_URL for class: com.microsoft.azure.util.AzureCredentials$Constants
    at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1002)
    at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1857)
    at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1833)
    at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3758)
    at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:51)
...
(20 additional frame(s) were not displayed)

Failed to run script file:/usr/share/jenkins/ref/init.groovy.d/setup-azure-cloud.groovy
```

**Comment by rtyler** [comment]
Fixed already with e7d6ce09da60ae21462aff0f9b758d33f0a435fd
