### ISSUE TITLE
AzureCloudException - No longer valid configuration for Azure VM Agents

### ISSUE THREAD

**Issue by rtyler** [CodeValet/codevalet#63]
https://sentry.io/codevalet/codevalet/issues/411569519/

```
IllegalArgumentException: 'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...)
    at com.microsoft.aad.adal4j.AuthenticationAuthority.detectAuthorityType(AuthenticationAuthority.java:190)
    at com.microsoft.aad.adal4j.AuthenticationAuthority.<init>(AuthenticationAuthority.java:73)
    at com.microsoft.aad.adal4j.AuthenticationContext.<init>(AuthenticationContext.java:108)
    at com.microsoft.azure.credentials.ApplicationTokenCredentials.acquireAccessToken(ApplicationTokenCredentials.java:148)
    at com.microsoft.azure.credentials.ApplicationTokenCredentials.getToken(ApplicationTokenCredentials.java:139)
...
(57 additional frame(s) were not displayed)

AzureCloudException: Exceeded maximum retry count 3
    at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:54)
    at com.microsoft.azure.vmagent.retry.ExponentialRetryStrategy.canRetry(ExponentialRetryStrategy.java:60)
    at com.microsoft.azure.vmagent.retry.ExponentialRetryStrategy.handleRetry(ExponentialRetryStrategy.java:48)
    at com.microsoft.azure.vmagent.retry.RetryTask.call(RetryTask.java:52)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
...
(3 additional frame(s) were not displayed)

ExecutionException: com.microsoft.azure.vmagent.exceptions.AzureCloudException: Exceeded maximum retry count 3
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.microsoft.azure.vmagent.util.ExecutionEngine.executeWithRetry(ExecutionEngine.java:41)
    at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.verifyConfiguration(AzureVMManagementServiceDelegate.java:1277)
    at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.verifyConfiguration(AzureVMManagementServiceDelegate.java:1251)
...
(9 additional frame(s) were not displayed)

AzureCloudException: None
    at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:54)
    at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:33)
    at com.microsoft.azure.vmagent.util.ExecutionEngine.executeWithRetry(ExecutionEngine.java:48)
    at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.verifyConfiguration(AzureVMManagementServiceDelegate.java:1277)
    at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.verifyConfiguration(AzureVMManagementServiceDelegate.java:1251)
...
(9 additional frame(s) were not displayed)

Error validating configuration
```

**Comment by rtyler** [comment]
Somewhere along the lines I fixed this
